### ISSUE TITLE
Ditch tenant name mapper script?

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/keycloak-scripts#3]
It looks like the `tenants-name-mapper` script could be an old version of `tenants-mapper`. In fact, the latter also considers Orchestra groups, i.e. Keycloak groups below level 1 groups (= Orchestra tenants).

Should we get rid of `tenants-name-mapper`? Does it still serve a purpose?

**Comment by chicco785** [comment]
it's a simpler version of it developed for some graphical ui (don't recall which one though)
